let medicines = [];
let activeReminder = null;
let reminderLoop;
let reminderTimeouts = {};

/* =========================
   LANGUAGE SYSTEM
========================= */

const translations = {
    en: {
        "AI Powered Healthcare Assistant": "AI Powered Healthcare Assistant",
        "AI Monitoring Online": "AI Monitoring Online",
        "Patient Name": "Patient Name",
        "Enter Patient Name": "Enter Patient Name",
        "Age": "Age",
        "Enter Age": "Enter Age",
        "Phone Number": "Phone Number",
        "Caregiver Number": "Caregiver Number",
        "Language": "Language",
        "Login": "Login",

        "Welcome!": "Welcome!",
        "Login Successful": "Login Successful",
        "AI Healthcare Assistant is Preparing...":
            "🤖 AI Healthcare Assistant is Preparing...",

        "AI Healthcare Monitoring System":
            "AI Healthcare Monitoring System",
        "AI Online": "AI Online",

        "Patient Profile": "Patient Profile",
        "Loading...": "Loading...",

        "Next Reminder": "⏰ Next Reminder",
        "No Reminder": "No Reminder",

        "Total Medicines": "Total Medicines",
        "Taken": "Taken",
        "Missed": "Missed",
        "Adherence": "Adherence",

        "Add Medicine": "💊 Add Medicine",
        "Medicine Name": "Medicine Name",
        "Enter Medicine Name": "Enter Medicine Name",
        "Dosage": "Dosage",
        "Example: 1 Tablet": "Example: 1 Tablet",
        "Reminder Time": "Reminder Time",

        "Today's Medicines": "Today's Medicines",

        "Call Caregiver": "📞 Call Caregiver",
        "Ambulance": "🚑 Ambulance",

        "AI Health Assistant": "🤖 AI Health Assistant",

        "HealthMessage":
            "Welcome!<br><br>Your health is being monitored.<br><br>Remember to take your medicines on time.",

        "Medicine Report": "📋 Medicine Report",
        "Total": "Total",
        "Activity Logs": "Activity Logs",
        "Dark Mode": "Dark Mode",
        "Logout": "Logout",

        "Medicine": "Medicine",
        "Time": "Time",
        "Status": "Status",
        "Download Report": "Download Report",

        "Please fill all fields": "Please fill all fields",
        "Fill all medicine details": "Fill all medicine details",
        "Call caregiver now?": "Call caregiver now?",
        "No caregiver number found.": "No caregiver number found.",
        "No medicine data available!": "No medicine data available!",

        "Medicine Missed Alert": "Medicine Missed Alert",
        "Calling ambulance": "Calling ambulance",
        "Calling caregiver": "Calling caregiver",
        "Pending": "Pending",

        "Reminder started for": "Reminder started for",
        "missed": "missed",
        "taken": "taken",
        "added": "added",

        "Name": "Name",
        "AgeLabel": "Age",
        "Phone": "Phone",

        "Generated by MEDICARE AI":
            "Generated by MEDICARE AI"
    },

    ta: {
        "AI Powered Healthcare Assistant":
            "AI மூலம் இயங்கும் சுகாதார உதவியாளர்",
        "AI Monitoring Online":
            "AI கண்காணிப்பு ஆன்லைனில் உள்ளது",

        "Patient Name": "நோயாளியின் பெயர்",
        "Enter Patient Name": "நோயாளியின் பெயரை உள்ளிடவும்",

        "Age": "வயது",
        "Enter Age": "வயதை உள்ளிடவும்",

        "Phone Number": "தொலைபேசி எண்",
        "Caregiver Number": "பராமரிப்பாளர் எண்",
        "Language": "மொழி",
        "Login": "உள்நுழைவு",

        "Welcome!": "வரவேற்கிறோம்!",
        "Login Successful": "உள்நுழைவு வெற்றிகரமாக முடிந்தது",

        "AI Healthcare Assistant is Preparing...":
            "🤖 AI சுகாதார உதவியாளர் தயாராகிறது...",

        "AI Healthcare Monitoring System":
            "AI சுகாதார கண்காணிப்பு அமைப்பு",

        "AI Online": "AI ஆன்லைனில் உள்ளது",

        "Patient Profile": "நோயாளி விவரம்",
        "Loading...": "ஏற்றப்படுகிறது...",

        "Next Reminder": "⏰ அடுத்த நினைவூட்டல்",
        "No Reminder": "நினைவூட்டல் இல்லை",

        "Total Medicines": "மொத்த மருந்துகள்",
        "Taken": "எடுத்துக்கொண்டது",
        "Missed": "தவறியது",
        "Adherence": "கடைப்பிடிப்பு",

        "Add Medicine": "💊 மருந்தைச் சேர்க்கவும்",
        "Medicine Name": "மருந்தின் பெயர்",
        "Enter Medicine Name":
            "மருந்தின் பெயரை உள்ளிடவும்",

        "Dosage": "அளவு",
        "Example: 1 Tablet":
            "உதாரணம்: 1 மாத்திரை",

        "Reminder Time": "நினைவூட்டல் நேரம்",

        "Today's Medicines": "இன்றைய மருந்துகள்",

        "Call Caregiver":
            "📞 பராமரிப்பாளரை அழைக்கவும்",

        "Ambulance": "🚑 ஆம்புலன்ஸ்",

        "AI Health Assistant":
            "🤖 AI சுகாதார உதவியாளர்",

        "HealthMessage":
            "வரவேற்கிறோம்!<br><br>உங்கள் உடல்நிலை கண்காணிக்கப்படுகிறது.<br><br>உங்கள் மருந்துகளை நேரத்திற்கு எடுத்துக்கொள்ளுங்கள்.",

        "Medicine Report":
            "📋 மருந்து அறிக்கை",

        "Total": "மொத்தம்",
        "Activity Logs": "செயல்பாட்டு பதிவுகள்",
        "Dark Mode": "இருள் பயன்முறை",
        "Logout": "வெளியேறு",

        "Medicine": "மருந்து",
        "Time": "நேரம்",
        "Status": "நிலை",
        "Download Report":
            "அறிக்கையைப் பதிவிறக்கவும்",

        "Please fill all fields":
            "அனைத்து புலங்களையும் நிரப்பவும்",

        "Fill all medicine details":
            "மருந்தின் அனைத்து விவரங்களையும் நிரப்பவும்",

        "Call caregiver now?":
            "இப்போது பராமரிப்பாளரை அழைக்கவா?",

        "No caregiver number found.":
            "பராமரிப்பாளர் எண் இல்லை.",

        "No medicine data available!":
            "மருந்து தரவு இல்லை!",

        "Medicine Missed Alert":
            "மருந்து தவறிய எச்சரிக்கை",

        "Calling ambulance":
            "ஆம்புலன்ஸ் அழைக்கப்படுகிறது",

        "Calling caregiver":
            "பராமரிப்பாளர் அழைக்கப்படுகிறார்",

        "Pending": "நிலுவையில்",

        "Reminder started for":
            "இதற்கான நினைவூட்டல் தொடங்கியது",

        "missed": "தவறியது",
        "taken": "எடுத்துக்கொள்ளப்பட்டது",
        "added": "சேர்க்கப்பட்டது",

        "Name": "பெயர்",
        "AgeLabel": "வயது",
        "Phone": "தொலைபேசி",

        "Generated by MEDICARE AI":
            "MEDICARE AI மூலம் உருவாக்கப்பட்டது"
    },

    hi: {
        "AI Powered Healthcare Assistant":
            "AI संचालित स्वास्थ्य सहायक",

        "AI Monitoring Online":
            "AI निगरानी ऑनलाइन है",

        "Patient Name": "मरीज का नाम",
        "Enter Patient Name":
            "मरीज का नाम दर्ज करें",

        "Age": "उम्र",
        "Enter Age": "उम्र दर्ज करें",

        "Phone Number": "फोन नंबर",
        "Caregiver Number":
            "देखभालकर्ता नंबर",

        "Language": "भाषा",
        "Login": "लॉगिन",

        "Welcome!": "स्वागत है!",
        "Login Successful":
            "लॉगिन सफल हुआ",

        "AI Healthcare Assistant is Preparing...":
            "🤖 AI स्वास्थ्य सहायक तैयार हो रहा है...",

        "AI Healthcare Monitoring System":
            "AI स्वास्थ्य निगरानी प्रणाली",

        "AI Online": "AI ऑनलाइन है",

        "Patient Profile":
            "मरीज की जानकारी",

        "Loading...": "लोड हो रहा है...",

        "Next Reminder":
            "⏰ अगला रिमाइंडर",

        "No Reminder":
            "कोई रिमाइंडर नहीं",

        "Total Medicines":
            "कुल दवाइयाँ",

        "Taken": "ली गई",
        "Missed": "छूटी",
        "Adherence": "पालन",

        "Add Medicine":
            "💊 दवा जोड़ें",

        "Medicine Name":
            "दवा का नाम",

        "Enter Medicine Name":
            "दवा का नाम दर्ज करें",

        "Dosage": "खुराक",

        "Example: 1 Tablet":
            "उदाहरण: 1 टैबलेट",

        "Reminder Time":
            "रिमाइंडर समय",

        "Today's Medicines":
            "आज की दवाइयाँ",

        "Call Caregiver":
            "📞 देखभालकर्ता को कॉल करें",

        "Ambulance":
            "🚑 एम्बुलेंस",

        "AI Health Assistant":
            "🤖 AI स्वास्थ्य सहायक",

        "HealthMessage":
            "स्वागत है!<br><br>आपके स्वास्थ्य की निगरानी की जा रही है।<br><br>अपनी दवाइयाँ समय पर लें।",

        "Medicine Report":
            "📋 दवा रिपोर्ट",

        "Total": "कुल",
        "Activity Logs":
            "गतिविधि लॉग",

        "Dark Mode": "डार्क मोड",
        "Logout": "लॉगआउट",

        "Medicine": "दवा",
        "Time": "समय",
        "Status": "स्थिति",

        "Download Report":
            "रिपोर्ट डाउनलोड करें",

        "Please fill all fields":
            "कृपया सभी फ़ील्ड भरें",

        "Fill all medicine details":
            "कृपया दवा की सभी जानकारी भरें",

        "Call caregiver now?":
            "क्या अभी देखभालकर्ता को कॉल करें?",

        "No caregiver number found.":
            "देखभालकर्ता का नंबर नहीं मिला।",

        "No medicine data available!":
            "दवा का डेटा उपलब्ध नहीं है!",

        "Medicine Missed Alert":
            "दवा छूटने की चेतावनी",

        "Calling ambulance":
            "एम्बुलेंस को कॉल किया जा रहा है",

        "Calling caregiver":
            "देखभालकर्ता को कॉल किया जा रहा है",

        "Pending": "लंबित",

        "Reminder started for":
            "के लिए रिमाइंडर शुरू हुआ",

        "missed": "छूट गई",
        "taken": "ली गई",
        "added": "जोड़ी गई",

        "Name": "नाम",
        "AgeLabel": "उम्र",
        "Phone": "फोन",

        "Generated by MEDICARE AI":
            "MEDICARE AI द्वारा बनाया गया"
    },

    te: {
        "AI Powered Healthcare Assistant":
            "AI ఆధారిత ఆరోగ్య సహాయకుడు",

        "AI Monitoring Online":
            "AI పర్యవేక్షణ ఆన్‌లైన్‌లో ఉంది",

        "Patient Name": "రోగి పేరు",
        "Enter Patient Name":
            "రోగి పేరు నమోదు చేయండి",

        "Age": "వయస్సు",
        "Enter Age":
            "వయస్సు నమోదు చేయండి",

        "Phone Number": "ఫోన్ నంబర్",
        "Caregiver Number":
            "సంరక్షకుని నంబర్",

        "Language": "భాష",
        "Login": "లాగిన్",

        "Welcome!": "స్వాగతం!",
        "Login Successful":
            "లాగిన్ విజయవంతమైంది",

        "AI Healthcare Assistant is Preparing...":
            "🤖 AI ఆరోగ్య సహాయకుడు సిద్ధమవుతున్నాడు...",

        "AI Healthcare Monitoring System":
            "AI ఆరోగ్య పర్యవేక్షణ వ్యవస్థ",

        "AI Online":
            "AI ఆన్‌లైన్‌లో ఉంది",

        "Patient Profile":
            "రోగి వివరాలు",

        "Loading...":
            "లోడ్ అవుతోంది...",

        "Next Reminder":
            "⏰ తదుపరి రిమైండర్",

        "No Reminder":
            "రిమైండర్ లేదు",

        "Total Medicines":
            "మొత్తం మందులు",

        "Taken":
            "తీసుకున్నారు",

        "Missed":
            "మిస్ అయ్యింది",

        "Adherence":
            "పాటింపు",

        "Add Medicine":
            "💊 మందును జోడించండి",

        "Medicine Name":
            "మందు పేరు",

        "Enter Medicine Name":
            "మందు పేరు నమోదు చేయండి",

        "Dosage":
            "మోతాదు",

        "Example: 1 Tablet":
            "ఉదాహరణ: 1 టాబ్లెట్",

        "Reminder Time":
            "రిమైండర్ సమయం",

        "Today's Medicines":
            "ఈరోజు మందులు",

        "Call Caregiver":
            "📞 సంరక్షకునికి కాల్ చేయండి",

        "Ambulance":
            "🚑 అంబులెన్స్",

        "AI Health Assistant":
            "🤖 AI ఆరోగ్య సహాయకుడు",

        "HealthMessage":
            "స్వాగతం!<br><br>మీ ఆరోగ్యం పర్యవేక్షించబడుతోంది.<br><br>మీ మందులను సమయానికి తీసుకోండి.",

        "Medicine Report":
            "📋 మందుల నివేదిక",

        "Total":
            "మొత్తం",

        "Activity Logs":
            "కార్యాచరణ లాగ్‌లు",

        "Dark Mode":
            "డార్క్ మోడ్",

        "Logout":
            "లాగ్ అవుట్",

        "Medicine":
            "మందు",

        "Time":
            "సమయం",

        "Status":
            "స్థితి",

        "Download Report":
            "నివేదికను డౌన్‌లోడ్ చేయండి",

        "Please fill all fields":
            "దయచేసి అన్ని ఫీల్డ్‌లను పూరించండి",

        "Fill all medicine details":
            "దయచేసి మందు వివరాలన్నీ పూరించండి",

        "Call caregiver now?":
            "ఇప్పుడు సంరక్షకునికి కాల్ చేయాలా?",

        "No caregiver number found.":
            "సంరక్షకుని నంబర్ కనుగొనబడలేదు.",

        "No medicine data available!":
            "మందుల డేటా అందుబాటులో లేదు!",

        "Medicine Missed Alert":
            "మందు మిస్ అయిన హెచ్చరిక",

        "Calling ambulance":
            "అంబులెన్స్‌కు కాల్ చేస్తోంది",

        "Calling caregiver":
            "సంరక్షకునికి కాల్ చేస్తోంది",

        "Pending":
            "పెండింగ్",

        "Reminder started for":
            "దీని కోసం రిమైండర్ ప్రారంభమైంది",

        "missed":
            "మిస్ అయ్యింది",

        "taken":
            "తీసుకున్నారు",

        "added":
            "జోడించబడింది",

        "Name":
            "పేరు",

        "AgeLabel":
            "వయస్సు",

        "Phone":
            "ఫోన్",

        "Generated by MEDICARE AI":
            "MEDICARE AI ద్వారా రూపొందించబడింది"
    }
};


/* =========================
   GET CURRENT LANGUAGE
========================= */

function getLanguage() {

    return localStorage.getItem("language") || "en";

}


/* =========================
   TRANSLATE TEXT
========================= */

function t(key) {

    const language = getLanguage();

    if (
        translations[language] &&
        translations[language][key]
    ) {

        return translations[language][key];

    }

    return translations.en[key] || key;

}


/* =========================
   APPLY LANGUAGE
========================= */

function applyLanguage() {

    const languageSelect =
        document.getElementById("language");

    if (!languageSelect) return;

    const language =
        languageSelect.value || "en";

    localStorage.setItem(
        "language",
        language
    );

    document.documentElement.lang =
        language;


    /* Normal text */

    document
        .querySelectorAll("[data-i18n]")
        .forEach(element => {

            const key =
                element.getAttribute("data-i18n");

            element.innerHTML =
                t(key);

        });


    /* Placeholders */

    document
        .querySelectorAll("[data-i18n-placeholder]")
        .forEach(element => {

            const key =
                element.getAttribute(
                    "data-i18n-placeholder"
                );

            element.placeholder =
                t(key);

        });


    /* Health assistant */

    const healthMessage =
        document.getElementById(
            "healthMessage"
        );

    if (healthMessage) {

        healthMessage.innerHTML =
            t("HealthMessage");

    }


    loadProfile();
    loadMedicines();
    loadLogs();
    updateDashboard();

}


/* =========================
   LANGUAGE CHANGE
========================= */

document.addEventListener(
    "DOMContentLoaded",
    function () {

        const selector =
            document.getElementById(
                "language"
            );

        if (!selector) return;

        selector.value =
            localStorage.getItem(
                "language"
            ) || "en";


        selector.addEventListener(
            "change",
            function () {

                localStorage.setItem(
                    "language",
                    selector.value
                );

                applyLanguage();

            }
        );

        applyLanguage();

    }
);


/* =========================
   PATIENT STORAGE
========================= */

function getPatientKey() {

    return localStorage.getItem(
        "patientPhone"
    );

}


function loadPatientMedicines() {

    const key =
        "medicines_" +
        getPatientKey();

    medicines =
        JSON.parse(
            localStorage.getItem(key)
        ) || [];

}


function savePatientMedicines() {

    const key =
        "medicines_" +
        getPatientKey();

    localStorage.setItem(
        key,
        JSON.stringify(medicines)
    );

}


function loadPatientLogs() {

    const key =
        "logs_" +
        getPatientKey();

    return JSON.parse(
        localStorage.getItem(key)
    ) || [];

}


function savePatientLogs(logs) {

    const key =
        "logs_" +
        getPatientKey();

    localStorage.setItem(
        key,
        JSON.stringify(logs)
    );

}


/* =========================
   CLOCK
========================= */

function updateClock() {

    const clock =
        document.getElementById(
            "clock"
        );

    if (clock) {

        clock.innerHTML =
            new Date().toLocaleTimeString();

    }

}

setInterval(
    updateClock,
    1000
);


/* =========================
   LOGIN
========================= */

function loginPatient() {

    const name =
        document.getElementById(
            "patientName"
        ).value;

    const age =
        document.getElementById(
            "patientAge"
        ).value;

    const phone =
        document.getElementById(
            "patientPhone"
        ).value;

    const caregiver =
        document.getElementById(
            "caregiverLogin"
        ).value;


    if (
        !name ||
        !age ||
        !phone ||
        !caregiver
    ) {

        alert(
            t("Please fill all fields")
        );

        return;

    }


    localStorage.setItem(
        "patientName",
        name
    );

    localStorage.setItem(
        "patientAge",
        age
    );

    localStorage.setItem(
        "patientPhone",
        phone
    );

    localStorage.setItem(
        "caregiver",
        caregiver
    );


    const language =
        document.getElementById(
            "language"
        ).value;

    localStorage.setItem(
        "language",
        language
    );


    loadPatientMedicines();


    document.getElementById(
        "loginSection"
    ).style.display = "none";


    document.getElementById(
        "welcomeSection"
    ).style.display = "flex";


    document.getElementById(
        "welcomeUser"
    ).innerHTML =
        `${t("Welcome!")}, ${name}!`;


    setTimeout(
        function () {

            document.getElementById(
                "welcomeSection"
            ).style.display = "none";


            document.getElementById(
                "dashboardSection"
            ).style.display = "block";


            document.getElementById(
                "welcomeText"
            ).innerHTML =
                `👋 ${t("Welcome!")}, ${name}!`;


            applyLanguage();

            loadProfile();
            loadMedicines();
            loadLogs();
            updateDashboard();

        },
        3000
    );

}


/* =========================
   AUTO LOGIN
========================= */

window.onload =
    function () {

        updateClock();


        const patient =
            localStorage.getItem(
                "patientName"
            );


        const selector =
            document.getElementById(
                "language"
            );


        if (selector) {

            selector.value =
                localStorage.getItem(
                    "language"
                ) || "en";

        }


        applyLanguage();


        if (patient) {

            loadPatientMedicines();


            document.getElementById(
                "loginSection"
            ).style.display = "none";


            document.getElementById(
                "welcomeSection"
            ).style.display = "flex";


            document.getElementById(
                "welcomeUser"
            ).innerHTML =
                `${t("Welcome!")}, ${patient}!`;


            setTimeout(
                function () {

                    document.getElementById(
                        "welcomeSection"
                    ).style.display = "none";


                    document.getElementById(
                        "dashboardSection"
                    ).style.display = "block";


                    document.getElementById(
                        "welcomeText"
                    ).innerHTML =
                        `👋 ${t("Welcome!")}, ${patient}!`;


                    loadProfile();
                    loadMedicines();
                    loadLogs();
                    updateDashboard();

                },
                3000
            );

        }

    };


/* =========================
   PROFILE
========================= */

function loadProfile() {

    const profile =
        document.getElementById(
            "patientProfile"
        );

    if (!profile) return;


    profile.innerHTML =

        `${t("Name")}: ${
            localStorage.getItem(
                "patientName"
            )
        }<br>

        ${t("AgeLabel")}: ${
            localStorage.getItem(
                "patientAge"
            )
        }<br>

        ${t("Phone")}: ${
            localStorage.getItem(
                "patientPhone"
            )
        }`;

}


/* =========================
   ADD MEDICINE
========================= */

function addMedicine() {

    const name =
        document.getElementById(
            "medicineName"
        ).value;

    const dosage =
        document.getElementById(
            "dosage"
        ).value;

    const time =
        document.getElementById(
            "medicineTime"
        ).value;


    if (
        !name ||
        !dosage ||
        !time
    ) {

        alert(
            t("Fill all medicine details")
        );

        return;

    }


    medicines.push({

        name: name,

        dosage: dosage,

        time: time,

        status: "Pending"

    });


    savePatientMedicines();


    addLog(
        name +
        " " +
        t("added")
    );


    loadMedicines();

    updateDashboard();

}


/* =========================
   LOAD MEDICINES
========================= */

function loadMedicines() {

    const list =
        document.getElementById(
            "medicineList"
        );

    if (!list) return;


    list.innerHTML = "";


    medicines.forEach(
        function (med, index) {

            const li =
                document.createElement(
                    "li"
                );


            li.innerHTML =

                `<b>${med.name}</b><br>

                ${t("Dosage")}:
                ${med.dosage}<br>

                ${t("Time")}:
                ${med.time}<br>

                ${t("Status")}:
                ${t(med.status)}<br><br>

                <button
                onclick="markTaken(${index})">

                ${t("Taken")}

                </button>`;


            list.appendChild(li);

        }
    );

}


/* =========================
   DASHBOARD
========================= */

function updateDashboard() {

    const total =
        medicines.length;


    const taken =
        medicines.filter(
            med =>
                med.status === "Taken"
        ).length;


    const missed =
        medicines.filter(
            med =>
                med.status === "Missed"
        ).length;


    const adherence =
        total === 0
            ? 0
            : Math.round(
                (taken / total) *
                100
            );


    document.getElementById(
        "totalMedicine"
    ).innerHTML = total;


    document.getElementById(
        "takenCount"
    ).innerHTML = taken;


    document.getElementById(
        "missedCount"
    ).innerHTML = missed;


    document.getElementById(
        "adherence"
    ).innerHTML =
        adherence + "%";


    document.getElementById(
        "reportTotal"
    ).innerHTML = total;


    document.getElementById(
        "reportTaken"
    ).innerHTML = taken;


    document.getElementById(
        "reportMissed"
    ).innerHTML = missed;


    document.getElementById(
        "reportAdherence"
    ).innerHTML =
        adherence + "%";


    const reportTable =
        document.getElementById(
            "reportTable"
        );


    reportTable.innerHTML = "";


    medicines.forEach(
        function (med) {

            reportTable.innerHTML +=

                `<tr>

                <td>${med.name}</td>

                <td>${med.dosage}</td>

                <td>${med.time}</td>

                <td>${t(med.status)}</td>

                </tr>`;

        }
    );

}


/* =========================
   MARK TAKEN
========================= */

function markTaken(index) {

    medicines[index].status =
        "Taken";


    savePatientMedicines();


    speechSynthesis.cancel();


    clearInterval(
        reminderLoop
    );


    if (
        reminderTimeouts[index]
    ) {

        clearTimeout(
            reminderTimeouts[index]
        );

    }


    activeReminder = null;


    addLog(
        medicines[index].name +
        " " +
        t("taken")
    );


    loadMedicines();

    updateDashboard();

}


/* =========================
   REMINDER CHECK
========================= */

function checkReminders() {

    const currentTime =
        new Date()
            .toTimeString()
            .substring(0, 5);


    medicines.forEach(
        function (
            medicine,
            index
        ) {

            if (
                medicine.time ===
                    currentTime &&

                medicine.status ===
                    "Pending"
            ) {

                triggerReminder(
                    medicine,
                    index
                );

            }

        }
    );

}

setInterval(
    checkReminders,
    1000
);


/* =========================
   VOICE REMINDER
========================= */

function triggerReminder(
    medicine,
    index
) {

    if (
        activeReminder ===
        index
    ) {

        return;

    }


    activeReminder =
        index;


    reminderLoop =
        setInterval(
            function () {

                const language =
                    getLanguage();


                let message = "";
                let voiceLanguage =
                    "en-US";


                if (
                    language === "ta"
                ) {

                    message =
                        `${medicine.name} மருந்தை எடுத்துக்கொள்ள வேண்டிய நேரம் இது`;

                    voiceLanguage =
                        "ta-IN";

                }

                else if (
                    language === "hi"
                ) {

                    message =
                        `${medicine.name} दवा लेने का समय हो गया है`;

                    voiceLanguage =
                        "hi-IN";

                }

                else if (
                    language === "te"
                ) {

                    message =
                        `${medicine.name} మందు తీసుకునే సమయం వచ్చింది`;

                    voiceLanguage =
                        "te-IN";

                }

                else {

                    message =
                        `Time to take ${medicine.name}`;

                    voiceLanguage =
                        "en-US";

                }


                const speech =
                    new SpeechSynthesisUtterance(
                        message
                    );


                speech.lang =
                    voiceLanguage;


                speech.rate =
                    0.9;


                speechSynthesis.cancel();

                speechSynthesis.speak(
                    speech
                );


            },
            5000
        );


    addLog(
        t("Reminder started for") +
        " " +
        medicine.name
    );


    document.getElementById(
        "nextReminder"
    ).innerHTML =
        `${medicine.name} (${medicine.time})`;


    reminderTimeouts[index] =
        setTimeout(
            function () {

                clearInterval(
                    reminderLoop
                );


                if (
                    medicines[index]
                        .status ===
                    "Pending"
                ) {

                    medicines[index]
                        .status =
                        "Missed";


                    savePatientMedicines();


                    addLog(
                        medicine.name +
                        " " +
                        t("missed")
                    );


                    sendMissedSMS(
                        medicine
                    );


                    loadMedicines();

                    updateDashboard();

                }


                activeReminder =
                    null;

            },
            60000
        );

}


/* =========================
   SMS
========================= */

function sendMissedSMS(
    medicine
) {

    const caregiver =
        localStorage.getItem(
            "caregiver"
        );


    if (!caregiver) return;


    const smsText =
        encodeURIComponent(

            `${t("Medicine Missed Alert")}\n` +

            `${t("Medicine")}: ${
                medicine.name
            }\n` +

            `${t("Time")}: ${
                medicine.time
            }`

        );


    window.location.href =
        `sms:${caregiver}?body=${smsText}`;


    setTimeout(
        function () {

            const confirmCall =
                confirm(
                    t(
                        "Call caregiver now?"
                    )
                );


            if (confirmCall) {

                window.location.href =
                    `tel:${caregiver}`;

            }

        },
        4000
    );

}


/* =========================
   LOG SYSTEM
========================= */

function addLog(message) {

    let logs =
        loadPatientLogs();


    logs.unshift(

        new Date()
            .toLocaleString() +

        " - " +

        message

    );


    savePatientLogs(
        logs
    );


    loadLogs();

}


function loadLogs() {

    const list =
        document.getElementById(
            "logList"
        );


    if (!list) return;


    list.innerHTML = "";


    const logs =
        loadPatientLogs();


    logs.forEach(
        function (log) {

            const li =
                document.createElement(
                    "li"
                );


            li.innerHTML = log;


            list.appendChild(
                li
            );

        }
    );

}


/* =========================
   OTHER FEATURES
========================= */

function callAmbulance() {

    addLog(
        t("Calling ambulance")
    );


    window.location.href =
        "tel:108";

}


function toggleDarkMode() {

    document.body.classList.toggle(
        "dark-mode"
    );

}


function logout() {

    localStorage.removeItem(
        "patientName"
    );

    location.reload();

}


function callCaregiver() {

    const caregiver =
        localStorage.getItem(
            "caregiver"
        );


    if (!caregiver) {

        alert(
            t(
                "No caregiver number found."
            )
        );

        return;

    }


    addLog(
        t("Calling caregiver")
    );


    window.location.href =
        `tel:${caregiver}`;

}


/* =========================
   DOWNLOAD REPORT
========================= */

function downloadReport() {

    const key =
        "medicines_" +
        getPatientKey();


    const medicinesData =
        JSON.parse(
            localStorage.getItem(
                key
            )
        ) || [];


    if (
        medicinesData.length ===
        0
    ) {

        alert(
            t(
                "No medicine data available!"
            )
        );

        return;

    }


    const {
        jsPDF
    } = window.jspdf;


    const pdf =
        new jsPDF();


    const patient =
        localStorage.getItem(
            "patientName"
        ) || "Patient";


    pdf.setFontSize(20);

    pdf.text(
        "MEDICARE AI",
        20,
        20
    );


    pdf.setFontSize(14);

    pdf.text(
        t("Medicine Report"),
        20,
        32
    );


    pdf.setFontSize(12);

    pdf.text(
        t("Patient Name") +
        ": " +
        patient,
        20,
        45
    );


    let y = 65;


    pdf.text(
        t("Medicine"),
        20,
        y
    );


    pdf.text(
        t("Dosage"),
        75,
        y
    );


    pdf.text(
        t("Time"),
        120,
        y
    );


    pdf.text(
        t("Status"),
        160,
        y
    );


    y += 10;


    medicinesData.forEach(
        function (med) {

            pdf.text(
                med.name || "",
                20,
                y
            );


            pdf.text(
                med.dosage || "",
                75,
                y
            );


            pdf.text(
                med.time || "",
                120,
                y
            );


            pdf.text(
                t(
                    med.status ||
                    "Pending"
                ),
                160,
                y
            );


            y += 10;


            if (y > 280) {

                pdf.addPage();

                y = 20;

            }

        }
    );


    pdf.text(
        t(
            "Generated by MEDICARE AI"
        ),
        20,
        y + 15
    );


    pdf.save(
        "MEDICARE_AI_Medicine_Report.pdf"
    );

}
